name: supervisor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI Components and Styling
  animate_do: ^4.2.0 # Animation library
  animated_text_kit: ^4.2.3 # Text animation effects
  cached_network_image: ^3.4.1 # Network image caching
  cupertino_icons: ^1.0.8 # iOS style icons
  flutter_svg: ^2.0.14 # SVG image rendering
  iconsax: ^0.0.8 # Modern icon pack
  shimmer: ^3.0.0 # Loading shimmer effect
  animations: ^2.0.11 # Animations
  pin_code_fields: ^8.0.1 # OTP input fields
  face_camera: ^0.1.4 # Face camera

  # Push Notifications
  onesignal_flutter: ^5.3.4

  # Navigation and Routing
  go_router: ^15.1.2 # Declarative routing

  # Internationalization and Localization
  easy_localization: ^3.0.7 # Multi-language support
  intl: ^0.20.2 # Internationalization utilities

  # State Management
  flutter_bloc: ^9.1.0 # BLoC pattern implementation

  # Data Storage and Persistence
  path_provider: ^2.1.5 # File system access
  shared_preferences: ^2.3.3 # Key-value storage
  sqflite: ^2.4.1 # SQLite database

  # Dependency Injection
  get_it: ^8.0.3 # Service locator
  injectable: ^2.5.0 # Code generation for DI

  # Networking
  dio: ^5.7.0 # HTTP client
  internet_connection_checker: ^3.0.1 # Network connectivity
  pretty_dio_logger: ^1.4.0 # Dio request/response logging

  # Utilities
#  app_links: ^6.4.0 # Deep linking
  path: ^1.9.0 # Path manipulation
  permission_handler: ^12.0.0+1 # Permission management
  #  sentry_flutter: ^8.14.0 # Error tracking
  share_plus: ^11.0.0 # Content sharing
  url_launcher: ^6.3.1 # URL handling
  uuid: ^4.5.1 # UUID generation
  image_picker: ^1.1.2 # Image picking
  geolocator: ^13.0.2 # Location services


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development Tools
  build_runner: ^2.4.13 # Code generation
#  change_app_package_name: ^1.4.0 # Package renaming
  flutter_lints: ^5.0.0 # Lint rules
  injectable_generator: ^2.7.0 # DI code generation

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900

    - family: Nrt
      fonts:
        - asset: assets/fonts/nrt/NRT-Reg.ttf
